---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # How many jobs to create in one go.
    batch_size: 25

    # How many jobs to create in total (should be a multiple of batch_size).
    total_count: 100

  tasks:
    - name: Set current_jorb variable.
      set_fact:
        current_jorb: 0

    - name: Create jobs.
      include_tasks: tasks/create_job.yml
      with_sequence: 'count={{ (total_count / batch_size) | int }}'

    - name: Wait until there are {{ total_count }} completed jobs.
      kubernetes.core.k8s_info:
        api_version: batch/v1
        kind: Job
        namespace: default
        field_selectors:
          - status.successful=1
      register: job_list
      until: (job_list.resources | length) == total_count
      retries: 7200  # 10 hours (with 5 second delay)
      delay: 5
