---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # How many jobs to create in one go.
    batch_size: 25

    # How many jobs to create in total (should be a multiple of batch_size).
    total_count: 100

    # Whether to clean up Jobs and Pods in-flight or leave them be.
    inflight_cleanup: true

  tasks:
    - name: Set current_jorb variable.
      set_fact:
        current_jorb: 0

    - name: Manage jobs.
      include_tasks: tasks/manage_jobs.yml
      with_sequence: 'count={{ (total_count / batch_size) | int }}'
